# Generated by Django 5.2 on 2025-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
