# Generated by Django 5.2 on 2025-06-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_media_app",
            "0003_alter_profile_bio_alter_profile_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
